### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by DevanB** [mvindahl/build-error-notifier#2]
Is this project still maintained?

If so - I would like to put in a PR to update the node-sass regex to the latest version, and add a watchify option.

If not - would you consider transferring the repository and npm module to be maintained by someone else (particularly me)?

Thanks!

**Comment by mvindahl** [comment]
Hello Devan,
I'm not personally using the tool for anything these days so yeah, it's somewhat unmaintained.

Transferring the project to you is an excellent suggestion. Not exactly sure how to do it but I'm sure that we can figure it out. Currently not at my computer but I think I can get I done Wednesday.

Cheers, /Martin

**Comment by DevanB** [comment]
Thanks for  the prompt response @mvindahl!

You can transfer GitHub repository by following [these steps](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-a-repository-to-another-user-account-or-to-an-organization).

And you can transfer the NPM module by doing one of two things:
1. Emailing support[at]npmjs[dot]com and CC'ing me (devan.beitel[at]gmail[dot]com) and they will walk through the steps.

OR
1. You can run `npm owner add devanb build-error-notifier` while in the package root directory. This will add me as an owner, and I can take over the package and remove you as an owner at that point.

-dev

**Comment by mvindahl** [comment]
Hi Devan,

I followed the steps that you listed above to transfer ownership. The github part is pending, awaiting approval from github. As for npm I think you now have the authorization to remove me.

Thanks for taking over -- and I'm happy that you find it useful enough to be worth it :)

/Martin

**Comment by DevanB** [comment]
@mvindahl 

I've approved the GitHub repository move, and I'll remove you from the npm module momentarily.

Hope you keep an eye on the project still!

-dev

**Comment by mvindahl** [comment]
My curiosity commands me to do that! :)

/Martin
